[0.333s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 94, in build
    available_commands = await self._get_available_commands(
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 192, in _get_available_commands
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/python3', '-W', 'ignore:setup.py install is deprecated', 'setup.py', '--help-commands'] to pass: /home/smkim/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 927, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/rosdistro-0.9.1.egg-info/entry_points.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smkim/ros2_tutorials/robot_ws/src/basic_pkg/setup.py", line 5, in <module>
    setup(
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 146, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/dist.py", line 278, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 286, in __init__
    self.finalize_options()
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/dist.py", line 630, in finalize_options
    ep(self)
  File "/home/smkim/.local/lib/python3.10/site-packages/setuptools/dist.py", line 647, in _finalize_setup_keywords
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1019, in <genexpr>
    dist.entry_points for dist in unique(distributions())
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 631, in entry_points
    return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 927, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
KeyboardInterrupt

